import Foundation

/// `RawRepresentable & Decodable` enums that decode unknown raw values to a
/// declared fallback case instead of throwing. Conformers provide
/// `fallback(for:)` — typically generated by `@FallbackDecodable`.
public protocol FallbackDecodable: RawRepresentable, Decodable
where RawValue: Decodable & Sendable {
    nonisolated static func fallback(for rawValue: RawValue) -> Self
}

extension FallbackDecodable {
    public nonisolated init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        let rawValue = try container.decode(RawValue.self)
        self = Self.from(rawValue: rawValue)
    }

    /// Same fallback semantics as `init(from:)`, for non-`Decodable` paths
    /// (APNs payloads, deep-link parsers).
    public nonisolated static func from(rawValue: RawValue) -> Self {
        if let value = Self(rawValue: rawValue) { return value }
        let fallback = Self.fallback(for: rawValue)
        FallbackDecodableLogger.sink(
            "Unknown raw \"\(String(describing: rawValue))\" for \(String(describing: Self.self)), fell back to .\(String(describing: fallback))"
        )
        return fallback
    }
}
